### ISSUE TITLE
High CPU usage from broker probe on minikube

### ISSUE THREAD

**Issue by apapia** [kafkaesque-io/pulsar-helm-chart#33]
When running locally on minikube on my laptop, I am experiencing very high CPU usage, effectively pegging all 3 cores available to the hyperkit VM.  It appears that this is because of the CPU intensive /brokers/healthcheck probe that is set to run every 10 seconds by default.  Setting this value to run once every 120 seconds, I see that the CPU usage goes down to a manageable 160m out of 3000m although with spikes every time the health check runs.

Perhaps the dev-values.yaml can be updated to reduce the broker probe interval or the chart can support disabling the probe entirely for dev purposes.

Thanks!

**Comment by cdbartholomew** [comment]
@apapia Thanks for reporting this issue.

I pushed a change to master (https://github.com/kafkaesque-io/pulsar-helm-chart/commit/df5c59034b322244d5806ff1408a0fe62e5c22de) that cleans up the default values for the various probes, makes it easy to disable the probes (enabled: no), and disables the somewhat heavy broker health-check probe in the dev values file. This will be included in the next release of the chart.

FWIW, I believe the broker health check is very useful. All the production clusters I work with have it enabled. If the broker is unable to pass messages via bookkeeper, then it is doesn't make any sense to allow it to keep serving traffic. And if the health check fails, then it does make sense to restart the broker to see if that clears the issue. I have seen this happen, not necessarily because of Pulsar but because of a bad underlying worker node, for example.  Since the broker is stateless, it is free to be rescheduled on a different node, therefore making the whole system self-healing, which is the point of a cloud-native architecture.

**Comment by cdbartholomew** [comment]
Actually, looking at this more closely, the checks are using the CLI command to run the health check. Pulsar CLI commands are terribly heavyweight, so I wonder if this is the cause for the large CPU hit. There is an endpoint that can be hit. When I originally added this feature, I opted for the CLI command because then I didn't have to deal with the TLS and token auth cases, but based on how much CPU this seems to be taking up, I think I should look at switching to the endpoint, especially for resource-constrained setups.

**Comment by cdbartholomew** [comment]
Switching to curl-based poll of the health endpoint has led to significant reduction in CPU usage on the brokers. 
![image](https://user-images.githubusercontent.com/22917476/78463695-00eadb00-76ae-11ea-9889-05f8d282c5df.png)

**Comment by apapia** [comment]
ETA on a release with this fix?  Thanks!

**Comment by cdbartholomew** [comment]
We are going to release this today.

**Comment by cdbartholomew** [comment]
The new release (1.0.16) is done. Please let me know if it fixes the issue. Cheers, Chris

**Comment by apapia** [comment]
Looks good.
